config/routes.rb
Rails.application.routes.draw do
  get 'simulator/index'
   
  resources :robots
  root 'simulator#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
  validates :positionX, presence: true
  validates :positionY, presence: true
  validates :direction, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def new
  end

  def index
    @robots = Robot.all
  end
  
  def show
    @robot = Robot.find(params[:id])
  end
  
  def create
    @robot = Robot.new(params.require(:robot).permit(:positionX, :positionY, :direction))
    @robot.save
    redirect_to @robot
  end
end

app/controllers/simulator_controller.rb
class SimulatorController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/helpers/simulator_helper.rb
module SimulatorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robots</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/index.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Position X</th>
    <th>Position Y</th>
    <th>Direction</th>
    <th></th>
  </tr>
 
  <% @robots.each do |robot| %>
      <%= robot.inspect %>
    <tr>
      <td><%= robot.id %></td>
      <td><%= robot.direction %></td>
      <td><%= robot.positionX %></td>
      <td><%= robot.positionY %></td>
      <td><%= link_to 'Show', robot_path(robot) %></td>
    </tr>
  <% end %>
</table>

app/views/robots/new.html.erb
<h1>New Robot</h1>

<%= form_for :robot, url:robots_path do |f| %>
  <p>
    <%= f.label :positionX %><br>
    <%= f.number_field :positionX %>
  </p> 
  <p>
    <%= f.label :positionY %><br>
    <%= f.number_field :positionY %>
  </p>
  <p>
    <%= f.label :direction %><br>
    <%= f.text_field :direction %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/robots/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @robot.id %>
</p>
<p>
  <strong>PositionX:</strong>
  <%= @robot.positionX %>
</p>
<p>
  <strong>PositionY:</strong>
  <%= @robot.positionY %>
</p>
<p>
  <strong>Direction:</strong>
  <%= @robot.direction %>
</p>

app/views/simulator/index.html.erb
<h1>Simulator#index</h1>
<p>Find me in app/views/simulator/index.html.erb</p>